### ISSUE TITLE
`dx-run-app-locally` terminates prematurely with `TypeError`

### ISSUE THREAD

**Issue by lgautier** [dnanexus/dx-toolkit#111]
```bash
$ dx-run-app-locally my-app -ireference=my-file.txt
About to run 'dx build --dry-run /opt/local/my-app'
dx build dry run successful

Using input JSON:
{
    "reference": {
        "$dnanexus_link": {
            "project": "project-<edited>", 
            "id": "file-<edited>"
        }
    }
}

Confirm running the executable with this input [Y/n]: Y
======
localjob-0:main
Input: reference = project-<edited>:file-<edited>
Logs:
Invoking main with {u'reference': {u'$dnanexus_link': {u'project': u'project-<edited>', u'id': u'file-<edited>'}}}
Traceback (most recent call last):
  File "<string>", line 76, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dxpy/utils/exec_utils.py", line 149, in run
    result = ENTRY_POINT_TABLE[job['function']](**job['input'])
TypeError: main() got an unexpected keyword argument 'reference'
localjob-0:main failed, exited with error code 1 after 0:00:00.200443
Local job workspaces can be found in: /opt/local/my-app/test-job-workspaces/2015-09-25-135028
```

Changing to an invalid parameter name is producing an earlier (and more meaningful) error message. 

```bash
$ dx-run-app-locally my-app -ifoo=my-file.txt
About to run 'dx build --dry-run /opt/local/my-app'
dx build dry run successful
---------------------------------------------------------------------------
DXCLIError                                Traceback (most recent call last)
/usr/local/bin/dx-run-app-locally in <module>()
     81 
     82 job_inputs = ExecutableInputs(input_spec=(dxapp_json.get('inputSpec') if running_main else None))
---> 83 job_inputs.update_from_args(args)
     84 
     85 # Extend job_inputs.inputs using "default" values in inputSpec

/usr/local/lib/python2.7/dist-packages/dxpy/cli/exec_io.pyc in update_from_args(self, args, require_all_inputs)
    728                     raise DXCLIError('An input was found that did not conform to the syntax: -i<input name>=<input value>')
    729                 self.add(self.executable._get_input_name(name) if \
--> 730                          self._desc.get('class') == 'workflow' else name, value)
    731             self._update_requires_resolution_inputs()
    732 

/usr/local/lib/python2.7/dist-packages/dxpy/cli/exec_io.pyc in add(self, input_name, input_value)
    526         if self.input_spec is not None:
    527             if input_name not in self.input_spec and self._desc.get('class') != 'workflow':
--> 528                 raise DXCLIError('Input field called "' + input_name + '" was not found in the input spec')
    529             elif input_name in self.input_spec:
    530                 input_class = self.input_spec[input_name]['class']

DXCLIError: Input field called "foo" was not found in the input spec
> /usr/local/lib/python2.7/dist-packages/dxpy/cli/exec_io.py(528)add()
    527             if input_name not in self.input_spec and self._desc.get('class') != 'workflow':
--> 528                 raise DXCLIError('Input field called "' + input_name + '" was not found in the input spec')
    529             elif input_name in self.input_spec:
```

**Comment by psung** [comment]
Hi @lgautier, I apologize for the delay in responding.

It looks like in the first case the parameter "reference" appears in the input specification (dxapp.json) but is not accepted as a parameter by the `main` function that you tagged with `@dxpy.entry_point('main')`. In each Python applet, the applet's inputs are used to invoke your `main` function and in particular this is done by keyword args. So you would need either to have that function explicitly accept all the inputs you are going to supply, `def main(reference, ...):` or accept kwargs, `def main(**kwargs):`.

**Comment by lgautier** [comment]
Hi @psung,

Thanks for the pointer.

It turns out that there was a typo in the function signature, which might be the cause of the error.

As it is troubleshooting is not made the easiest: the traceback does not refer anywhere to the source of the error. It would seem (much) better to prevent `exec_utils.run()` from obfuscating the source of the error.

**Comment by kislyuk** [comment]
Hi @lgautier,

Thanks for the suggestion. I agree that `exec_utils.run()` should not mask the original stack trace. We will see what we can do to avoid that.

**Comment by lgautier** [comment]
A (closing) note for anyone ending up here.

The root of my issue was typo in a variable name in the Python script (app implemented in Python), which caused an exception during the call to the decorated main function (`@dxpy.entry_point('main')`).
