### ISSUE TITLE
dx run fails when using batch-tsv file

### ISSUE THREAD

**Issue by aledj2** [dnanexus/dx-toolkit#1168]
I have tried to set off multiple instances of an applet, where the input is an array of files.
I have used generate_batch_inputs to create a list of files to be processed, but when I use the dx run command and --batch-tsv input I get an error saying that this can't map to an input (traceback below).
I am using v0.344.0

Traceback (most recent call last):
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/utils/batch_utils.py", line 112, in _type_convert
    return _type_convert_array(val, klass)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/utils/batch_utils.py", line 98, in _type_convert_array
    raise Exception("Malformed array {}".format(val))
Exception: Malformed array project-GYfzyz80Y8fVK4P494P6Yb9k:file-GYg2bq00Y8fxF822Jkv6qV40

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/scripts/dx.py", line 6190, in main
    args.func(args)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/scripts/dx.py", line 3538, in run
    run_body(args, handler, dest_proj, dest_path)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/scripts/dx.py", line 3150, in run_body
    run_batch_all_steps(args, executable, dest_proj, dest_path, input_json, run_kwargs)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/scripts/dx.py", line 2989, in run_batch_all_steps
    b_args = batch_launch_args(executable, input_json, args.batch_tsv)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/utils/batch_utils.py", line 182, in batch_launch_args
    val_w_correct_type, ref_files = _type_convert(val.strip(), klass)
  File "/home/aled/.local/lib/python3.8/site-packages/dxpy/utils/batch_utils.py", line 117, in _type_convert
    raise Exception("value={} cannot be converted into class {}".format(val, klass))
Exception: value=project-GYfzyz80Y8fVK4P494P6Yb9k:file-GYg2bq00Y8fxF822Jkv6qV40 cannot be converted into class array:file

**Comment by sclan** [comment]
The file ID values have to be in square brackets. This is mentioned at the later part of the following documentation page in the batch file generation section:
https://documentation.dnanexus.com/user/running-apps-and-workflows/running-batch-jobs#generate-batch-file

Example command for adding square brackets around the project-xxx:file-yyy values in the batch file from the page (for the 4th and 5th column):
"head -n 1 dx_batch.0000.tsv > temp.tsv && tail -n +2 dx_batch.0000.tsv | awk '{sub($4, "[&]"); print}' | awk '{sub($5, "[&]"); print}' >> temp.tsv; tr -d '\r' < temp.tsv > new.tsv; rm temp.tsv"

A side note: at this time, the batch feature on CLI only supports applets, apps, and workflows.
