### ISSUE TITLE
Failure during dx-app-wizard on Python 3.6.1

### ISSUE THREAD

**Issue by claymcleod** [dnanexus/dx-toolkit#217]
Hi DNAnexus,

Looks like Python 3.6 may have broken the dx-app-wizard code. See below:

```
Access Permissions
If you request these extra permissions for your app, users will see this fact when
launching your app, and certain other restrictions will apply. For more information, see
https://wiki.dnanexus.com/App-Permissions.

Access to the Internet (other than accessing the DNAnexus API).
Will this app need access to the Internet? [y/N]: n

Direct access to the parent project. This is not needed if your app specifies
outputs,     which will be copied into the project after it's done running.
Will this app need access to the parent project? [y/N]:

System Requirements

Common instance types:
Traceback (most recent call last):
  File "../.conda/envs/python3.6/bin/dx-app-wizard", line 11, in <module>
    sys.exit(main())
  File "../.conda/envs/python3.6/lib/python3.6/site-packages/dxpy/scripts/dx_app_wizard.py", line 370, in main
    column_names=InstanceTypesCompleter.instance_types.values()[0]._fields))
TypeError: 'odict_values' object does not support indexing```

**Comment by kpjensen** [comment]
Hi Clay,

Thanks for reporting this issue. The fix for this should move to production during our toolkit release next week.

**Comment by claymcleod** [comment]
Great, thank you!
