### ISSUE TITLE
upload method doesn't work correctly

### ISSUE THREAD

**Issue by pkokoshnikov** [dnanexus/dx-toolkit#223]
Hi guys, 

I’m working on upload task. And I've faced with strange behaviour. 

This code 
`
DXRecord.newRecordWithEnvironment(environment).setProject(project).addTypes(types).putAllProperties().setDetails(details).build();
`
works correctly.

But this
`
DXFile.newFileWithEnvironment(environment).setProject(project).addTypes(types).putAllProperties(properties).upload(bytes).setName(name).build();
`
produces exception 

java.lang.RuntimeException: javax.net.ssl.SSLPeerUnverifiedException: Host name 'dnanexus-platform-upload-prod.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)

at com.dnanexus.DXFile$Builder.build(DXFile.java:92)
	at com.natera.test.dsl.service.DnaNexusService.uploadFile(DnaNexusService.java:372)
	at com.natera.test.horizon.process.TestUpload.upload(TestUpload.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'dnanexus-platform-upload-prod.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:466)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.dnanexus.DXFile.executeRequestWithRetry(DXFile.java:629)
	at com.dnanexus.DXFile.partUploadRequest(DXFile.java:952)
	at com.dnanexus.DXFile.access$500(DXFile.java:60)
	at com.dnanexus.DXFile$FileApiOutputStream.close(DXFile.java:460)
	at com.dnanexus.DXFile.upload(DXFile.java:992)
	at com.dnanexus.DXFile$Builder.build(DXFile.java:90)
	... 30 more

Project, environment and e.t.c are same. I tried to add s3.amazonaws.com certificate to java cacerts, but it doesn’t change anything.

Could you please help me to solve this issue?

I use version number 0.219.0

P.S. When I do upload from dx-toolkit cli util it works correctly, problem is tied with java.

**Comment by commandlinegirl** [comment]
Hello!

Thanks for letting us know. Does the issue persist or it's intermittent? It looks like the certificate does match *.s3.amazonaws.com. I'll check if I can reproduce it and will get back to you. 

Best,
Ola

**Comment by commandlinegirl** [comment]
Quick question: Could you check which http client and which version you are using and if it requires SNI explicitly enabled (so that wildcard matching works properly)?

**Comment by pkokoshnikov** [comment]
Hi Ola,

I've checked stacktrace and found that my version of dnanexus uses org.apache.httpcomponents:httpclient:4.4. I hope it helps you

**Comment by commandlinegirl** [comment]
Thanks, Pavel. Could you let us know your JDK version? I’ll try to reproduce it with the same version (using JDK8 with the current 0.227.0 or 0.219.0 version of dx-toolkit I couldn't repro it). When running JDK7 or higher SNI [should enabled by default](https://stackoverflow.com/questions/25854543/how-to-enable-sni-in-http-request-using-apache-httpcomponents-httpclient). Thanks!

**Comment by pkokoshnikov** [comment]
Hi, I use 1.8.0_60

**Comment by pkokoshnikov** [comment]
I know about that it have to work by default...

**Comment by pkokoshnikov** [comment]
I tried to update httpclient and httpcore and now it works corretly
`
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>4.5.2</version>
            </dependency>

            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>4.4.4</version>
            </dependency>
`
