### ISSUE TITLE
dnanexus java api: infinite socket timeouts

### ISSUE THREAD

**Issue by vpiyanov** [dnanexus/dx-toolkit#286]
DXSearch call can hang in the ``SocketInputStream.socketRead0()`` if network connection is unstable.
The root cause is that DXHTTPRequest creates Apache HttpClient with default parameters. As result the infinite socket timeout is used.

The issue can be reproduce with a synthetic test case:
```
    @Test(expected = DXHTTPException.class)
    public void test() throws Exception {
        new Thread(() -> {
            try {
                System.err.println("start server thread");
                new ServerSocket(17291).accept();
                System.err.println("accepted");
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }).start();

        DXEnvironment environment = DXEnvironment.Builder.fromDefaults()
                                                         .setApiserverHost("localhost")
                                                         .setApiserverPort(17291)
                                                         .build();

        DXSearch.findDataObjectsWithEnvironment(environment).withClassRecord().execute().asList();
    }
```
Expected result: The ``DXHTTPException`` exception should be thrown.
Actual result: Test hangs with stacktrace:
```
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <0x00000006cd309320> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	- locked <0x00000006cd309330> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.dnanexus.DXHTTPRequest.requestImpl(DXHTTPRequest.java:282)
	at com.dnanexus.DXHTTPRequest.request(DXHTTPRequest.java:189)
	at com.dnanexus.DXAPI.systemFindDataObjects(DXAPI.java:24061)
	at com.dnanexus.DXSearch$FindDataObjectsResult$FindDataObjectsResultPage.<init>(DXSearch.java:905)
	at com.dnanexus.DXSearch$FindDataObjectsResult$ResultIterator.issueQuery(DXSearch.java:959)
	at com.dnanexus.DXSearch$FindDataObjectsResult$ResultIterator.issueQuery(DXSearch.java:942)
	at com.dnanexus.DXSearch$PaginatingFindResultIterator.<init>(DXSearch.java:2034)
	at com.dnanexus.DXSearch$PaginatingFindResultIterator.<init>(DXSearch.java:2018)
	at com.dnanexus.DXSearch$FindDataObjectsResult$ResultIterator.<init>(DXSearch.java:948)
	at com.dnanexus.DXSearch$FindDataObjectsResult$ResultIterator.<init>(DXSearch.java:943)
	at com.dnanexus.DXSearch$FindDataObjectsResult.iterator(DXSearch.java:1053)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at com.dnanexus.DXSearch$ObjectProducerImpl.asList(DXSearch.java:2002)
	at com.dnanexus.DXSearch$FindDataObjectsResult.asList(DXSearch.java:893)
```
Possible workaround:
Set timeouts on Apache HttpClient default ``RequestConfig``.
```
        FieldUtils.writeField(RequestConfig.DEFAULT, "socketTimeout", 1000, true);
        FieldUtils.writeField(RequestConfig.DEFAULT, "connectTimeout", 1000, true);
```

Possible fixes: allow the API user to configure socket timeouts in ``DXEnvironment`` or hardcode some reasonable timeout values (e.g. 1000-5000ms) in the ``DXHTTPRequest``.

**Comment by commandlinegirl** [comment]
Hello! Thank you for bringing it into our attention and the suggestion! We will look into that.

**Comment by Diover** [comment]
Hi. 
We stumbled upon this too. Is there any time estimate, when it can be fixed and included into the next release? Hanged connections occupy threads and prevent them from being interrupted. It's really annoying...

**Comment by commandlinegirl** [comment]
This is implemented (thanks, @pkokoshnikov) and is on it's way to prod next week.
