### ISSUE TITLE
dxpy is not `pip install -e`-able

### ISSUE THREAD

**Issue by pkaleta** [dnanexus/dx-toolkit#404]
I get this when running `pip install -e "git+git@github.com:dnanexus/dx-toolkit.git#egg=dxpy&subdirectory=src/python`:

```
⋊> ~/yyy on xxx ⨯ pip install -e "git+git@github.com:dnanexus/dx-toolkit.git#egg=dxpy&subdirectory=src/python"
Obtaining dxpy from git+git@github.com:dnanexus/dx-toolkit.git#egg=dxpy&subdirectory=src/python
  Updating ./src/dxpy clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/piotr/yyy/src/dxpy/src/python/setup.py", line 27, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'dxpy', 'toolkit_version.py')) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/piotr/yyy/src/dxpy/src/python/dxpy/toolkit_version.py'
```

**Comment by orodeh** [comment]
The supported method of install dxpy is `pip install dxpy`. We do not support `pip install -e`. We haven't seen the need for it, nor widespread demand. 

Sorry,
     Ohad.
