### ISSUE TITLE
dx run app-cloud_workstation --allow-ssh mostly doesn't work

### ISSUE THREAD

**Issue by Sames-Jtudd** [dnanexus/dx-toolkit#408]
Self explanatory really. 

Most of the time executing the above command results in an error. Sometimes it works mostly it doesn't. 

running CentOS Linux release 7.1.1503 

$ dx run app-cloud_workstation –-allow-ssh
Traceback (most recent call last):
  File "../Programs/dx-toolkit/bin/dx", line 11, in <module>
    sys.exit(main())
  File "../Programs/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 5795, in main
    args = parser.parse_args(args_list)
  File "/usr/lib64/python2.7/argparse.py", line 1691, in parse_args
    self.error(msg % ' '.join(argv))
  File "../Programs/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 4017, in error
    message = message.decode(sys_encoding)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 24: ordinal not in range(128)

any help appreciated, thanks

**Comment by Sames-Jtudd** [comment]
Hi Kurt, thanks for getting back to me.

Sadly that suggestion didn’t have the desired effect.

Any other ideas?

Thanks

Jamie

**Comment by kpjensen** [comment]
I was able to duplicate this by exactly copying the command you attempt to run.
The error for char `u'\u2013'` is because the `–-allow-ssh` string contains en-dash unicode characters, not the expected ascii hyphen.
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 24: ordinal not in range(128)
```
```
# With en-dash
[root@33e6422aa70c dx-toolkit]# dx run app-cloud_workstation –-allow-ssh
Traceback (most recent call last):
  File "/dx-toolkit/bin/dx", line 11, in <module>
    sys.exit(main())
  File "/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 5802, in main
    args = parser.parse_args(args_list)
  File "/usr/lib64/python2.7/argparse.py", line 1691, in parse_args
    self.error(msg % ' '.join(argv))
  File "/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 4020, in error
    message = message.decode(sys_encoding)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 24: ordinal not in range(128)
```
```
# With hyphen
[root@33e6422aa70c dx-toolkit]# dx run app-cloud_workstation --allow-ssh "*"

Select an optional parameter to set by its # (^D or <ENTER> to finish):

 [0] Maximum Session Length (suffixes allowed: s, m, h, d, w, M, y) (max_session_length) [default="1h"]
 [1] Files (fids)
 [2] Snapshot (snapshot)
```
Can you try pasting the command with hyphens to see if that succeeds? This could explain why only sometimes it works for you.

**Comment by Sames-Jtudd** [comment]
Wow I would never have spotted that.

Funny thing is I think I copied the command from the DNAnexus website.

Thanks I appreciate your help.
