### ISSUE TITLE
Missing attribute message on Python 3

### ISSUE THREAD

**Issue by pkaleta** [dnanexus/dx-toolkit#438]
On python3 `message` was removed:

```
Traceback (most recent call last):
  File "/Users/piotr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dxpy/scripts/dx.py", line 2614, in build
    dx_build_app.build(args)
  File "/Users/piotr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dxpy/scripts/dx_build_app.py", line 1002, in build
    json.loads(args.extra_args) if args.extra_args else {})
  File "/Users/piotr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dxpy/scripts/dx_build_app.py", line 936, in _build_app
    print("Error: %s" % (e.message,), file=sys.stderr)
AttributeError: 'AppBuilderException' object has no attribute 'message'
```

**Comment by pkaleta** [comment]
cc @orodeh

**Comment by orodeh** [comment]
This has been fixed in master.
