### ISSUE TITLE
0.276: source environment - not able to import argcomplete

### ISSUE THREAD

**Issue by sgaj** [dnanexus/dx-toolkit#488]
Hello,

Unpacking and sourcing the environment of `dx-toolkit-v0.276.0-centos-amd64.tar.gz` gave the following error (Python 2.7.5):

```
Traceback (most recent call last):
  File "./dx-toolkit/bin/register-python-argcomplete", line 23, in "module>
    import argcomplete
ImportError: No module named argcomplete
```

Resolved this by copying the argcomplete folder from 
`./dx-toolkit/share/dnanexus/lib/python2.7/site-packages/` 
to 
`./dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/packages/`

Unsure if this also affects other OSes.

**Comment by aleonti** [comment]
Was also having this problem, thanks so much for sharing! After implementing the fix, though, I got the following error:

```
ImportError: No module named dxpy.scripts.dx
```

Not sure why I'm having so many issues finding the necessary scripts/modules?

**Comment by radlinsky** [comment]
On Linux, I saw the same error when I tried sourcing the environemnt:
`ImportError: No module named argcomplete`

I was in a python virtual env, and here is what I did to fix the problem:
0) source /path/to/python3/env/bin/activate
1) pip install argcomplete
2) pip install dxpy
3) run the following to determine the path to python:
`which python`
4) Copied the path (replacing tilde with absolute path), and used this path to replace the shebang (top line) in the following files:
dx-toolkit/bin/dx
dx-toolkit/bin/register-python-argcomplete

**Comment by Ikayanjoh** [comment]
May I request some help here! 
I did follow above instruction on how to install dx-toolkit but still getting same error.

$ tar -xzf dx-toolkit*.tar.gz
$ source dx-toolkit/environment

Traceback (most recent call last):
  File "./dx-toolkit/bin/register-python-argcomplete", line 27, in "module>
    import argcomplete
ImportError: No module named argcomplete**_**

Am I missing anything?

**Comment by japacheco42** [comment]
I also tried all of the above & still get same error, in Linux, verified using Python 2.7.  Any other suggestions?  The (argcomplete & dxpy) packages appear to be actually installed, when I tried pip install argcomplete (or dxpy) I get message back:  Requirement already satisfied: argcomplete in ...../software/anaconda2/lib/python2.7/site-packages (1.0.0) & similar messages for dxpy, although that also gives errors/warnings such as "oncotator 1.9.8.0 has requirement numpy==1.11.0, but you'll have numpy 1.14.0 which is incompatible."

**Comment by xihaoli** [comment]
> On Linux, I saw the same error when I tried sourcing the environemnt:
> `ImportError: No module named argcomplete`
> 
> I was in a python3 virtual env, and here is what I did to fix the problem:
> 
> 1. source /path/to/python3/env/bin/activate
> 2. pip install argcomplete
> 3. pip install dxpy
> 4. run the following to determine the path to python:
>    `which python`
> 5. Copied the path (replacing tilde with absolute path), and used this path to replace the shebang (top line) in the following files:
>    dx-toolkit/bin/dx
>    dx-toolkit/bin/register-python-argcomplete

Thank you so much for the solution!!!
