### ISSUE TITLE
Can't pip install dxpy newest version

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dx-toolkit#539]
Getting this error when installing. 
```
Collecting dxpy>=0.280.0 (from -r requirements.txt (line 17))
  Downloading https://pypi..../root/pypi/%2Bf/15e/c8e7b7d2d4fb1/dxpy-0.285.0.tar.gz (454kB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-t209ignz/dxpy/setup.py", line 54, in <module>
        readme_content = fh.read()
      File "/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3707: ordinal not in range(128)
```

**Comment by jtratner** [comment]
I think, ideally, you would pass an `encoding` to `open()` rather than assuming `utf-8`. Or not have special characters in the Readme

**Comment by kpjensen** [comment]
Thanks for reporting, I updated Pypi with `0.285.1` which removes the non-ascii character from the Readme. This should fix the install error, let me know if it does not.
