### ISSUE TITLE
dx-app-wizard fails on instance type selection

### ISSUE THREAD

**Issue by claymcleod** [dnanexus/dx-toolkit#602]
This is what I get every time I try to run `dx-app-wizard` on both Python2.7 and Python3.6.

```
Direct access to the parent project. This is not needed if your app specifies outputs,
which will be copied into the project after it's done running.
Will this app need access to the parent project? [y/N]:

System Requirements

Common AWS instance types:
Traceback (most recent call last):
  File "/home/cmcleod/.conda/envs/bio-2.7/bin/dx-app-wizard", line 8, in <module>
    sys.exit(main())
  File "/home/cmcleod/.conda/envs/bio-2.7/lib/python2.7/site-packages/dxpy/scripts/dx_app_wizard.py", line 371, in main
    column_names=list(InstanceTypesCompleter.instance_types.values())[0]._fields))
  File "/home/cmcleod/.conda/envs/bio-2.7/lib/python2.7/site-packages/dxpy/compat.py", line 107, in write
    TextIOWrapper.write(self, text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u250c' in position 5: ordinal not in range(128)
```

**Comment by kpjensen** [comment]
Is this still an issue? Usually it can be fixed by setting the following env variable.
```
export PYTHONIOENCODING=UTF-8
```
