### ISSUE TITLE
API break in get_dxlink_ids()

### ISSUE THREAD

**Issue by Ben-Habermeyer** [dnanexus/dx-toolkit#772]
Hi DNAnexus support,

When updating `dxpy` from `0.265.0` to latest `0.322.1` that there is an API break in the `get_dxlink_ids()` function, which I could not find documented anywhere in https://github.com/dnanexus/dx-toolkit/blob/master/CHANGELOG.md

Basically the new api accepts jobs, and raises `DXError` instead of `KeyError`

Could you point me to the changelog for the version where this API was updated? (breaking a bunch of existing behavior/tests in an app I am developing).

job:
```
dx_link = {
            '$dnanexus_link': {
              'job': 'job-FV78Xgj0gzY3j23Q3k1G4yj0',
              'field': 'flowcell_archive'
            }
        }

# 0.265.0 raises KeyError
>>> dxpy.get_dxlink_ids(dx_link)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhaberme/git/reorg-app/.venv/lib/python3.6/site-packages/dxpy/bindings/dxdataobject_functions.py", line 90, in get_dxlink_ids
    return link['$dnanexus_link']['id'], link['$dnanexus_link'].get('project')
KeyError: 'id'

# 0.322.1 does not
>>> dxpy.get_dxlink_ids(dx_link)
('job-FV78Xgj0gzY3j23Q3k1G4yj0', 'flowcell_archive')`
```

analysis:
```
dx_link = {
            '$dnanexus_link': {
              'analysis': 'analysis-FV4ZYzj0KQ760qv7GFGk66zF',
              'stage': 'stage-0',
              'field': 'manifest'
            }
        }

# 0.265.0 raises KeyError
>>> dxpy.get_dxlink_ids(dx_link)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhaberme/git/reorg-app/.venv/lib/python3.6/site-packages/dxpy/bindings/dxdataobject_functions.py", line 90, in get_dxlink_ids
    return link['$dnanexus_link']['id'], link['$dnanexus_link'].get('project')
KeyError: 'id'

# 0.322.1 raises DXError
>>> dxpy.get_dxlink_ids(dx_link)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhaberme/.pyenv/versions/3.6.13/lib/python3.6/site-packages/dxpy/bindings/dxdataobject_functions.py", line 115, in get_dxlink_ids
    raise DXError('Invalid link: %r' % link)
dxpy.exceptions.DXError: Invalid link: {'$dnanexus_link': {'analysis': 'analysis-FV4ZYzj0KQ760qv7GFGk66zF', 'stage': 'stage-0', 'field': 'manifest'}}
```

**Comment by kpjensen** [comment]
Hello, this behavior looks to have changed in `dxpy` version`0.280.0` https://github.com/dnanexus/dx-toolkit/blob/master/CHANGELOG.md#2800---20190418 after https://github.com/dnanexus/dx-toolkit/commit/a86d952d5142dc01a18d64f50d5049a0f7e39dbe was merged.

**Comment by emiloslavsky** [comment]
@Ben-Habermeyer , hope the explanation above is sufficient.  Please re-open if something is not clear.
