### ISSUE TITLE
KeyError while searching for failed jobs

### ISSUE THREAD

**Issue by lemieuxl** [dnanexus/dx-toolkit#787]
Using `dxpy` version 0.325.1, I get the following `KeyError` while searching for failed jobs.

```console
$ dx find jobs --state failed
Traceback (most recent call last):
  File "/opt/Python-3.10_virtualenv/lib64/python3.10/site-packages/dxpy/scripts/dx.py", line 2248, in find_executions
    process_tree(descriptions[roots[root]], executions_by_parent, descriptions)
  File "/opt/Python-3.10_virtualenv/lib64/python3.10/site-packages/dxpy/scripts/dx.py", line 2164, in process_tree
    tree, root = build_tree(result['id'], executions_by_parent, execution_descriptions, is_cached_result)
  File "/opt/Python-3.10_virtualenv/lib64/python3.10/site-packages/dxpy/scripts/dx.py", line 2145, in build_tree
    root_string = get_find_executions_string(execution_descriptions[root],
  File "/opt/Python-3.10_virtualenv/lib64/python3.10/site-packages/dxpy/utils/describe.py", line 1154, in get_find_executions_string
    runtime = datetime.timedelta(seconds=int(desc['stoppedRunning']-desc['startedRunning'])//1000)
KeyError: 'stoppedRunning'
```

I don't know if it helps, but my jobs failed for two main reasons: "_The machine running the job was terminated by the cloud provider_" and "_The machine running the job became unresponsive_".

**Comment by adrianodemarino** [comment]
I solved this issue adding: 
```
  if desc['state'] == 'failed':
      pass
  else:
      runtime = datetime.timedelta(seconds=int(desc['stoppedRunning']-desc['startedRunning'])//1000)
      cached_and_runtime_strs.append("runtime " + str(runtime))
```
to line: 1158 in describe.py
