### ISSUE TITLE
dx download failed with Python 3.11

### ISSUE THREAD

**Issue by ptdtan** [dnanexus/dx-toolkit#896]
Hi,

`dx download` failed with any file path in python `3.11`. The error message is straightforward: `re.error: global flags not at the start of the expression`. See the full error message below.
```python
(py3.11) ➜  ~ dx download cellranger_bundle
Traceback (most recent call last):
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/site-packages/dxpy/scripts/dx.py", line 6140, in main
    args.func(args)
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/site-packages/dxpy/scripts/dx.py", line 1976, in download_or_cat
    download(args)
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/site-packages/dxpy/cli/download.py", line 229, in download
    matching_folders = pathmatch.filter(folder_listing, abs_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/site-packages/dxpy/utils/pathmatch.py", line 33, in filter
    _cache[pat] = re.compile(res)
                  ^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tphan@dnanexus.com/opt/miniconda3/envs/py3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 20
```

The root cause is here:
https://github.com/dnanexus/dx-toolkit/blob/43676d3965434fa91b7577c6e9015999aee741d2/src/python/dxpy/utils/pathmatch.py#L80

In python 3.11, global inline flags (e.g. (?i)) can now only be used at the start of regular expressions. Reference: https://docs.python.org/3/whatsnew/3.11.html.

**Comment by ptdtan** [comment]
Fixed in #907
